// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json({
    all: [
      "Anita: Ven, Juanito. Vamos a entrar a esta alfarería. Al cabo que no está Don Peter.",
      "(Entra Anita y empieza a ver las cosas sobre la mesa)",
      "Juanito: Anita, no deberíamos estar aquí.",
      "(Anita toma una maceta)",
      "Juanito: ¡¿Qué haces?! ¡Vas a romper esas cosas!",
      "Anita: Tranquilo, Juanito. No pasa nada.",
      "Anita: Mira, Juanito. Esta maceta me gusta mucho. Si yo tuviera una casa la pondría en un lugar donde todos la pudieran ver",
      "(Anita pone la maceta en las manos de Juanito)",
      "Juanito: Sí, Anita. Pero mejor la ponemos aquí (pone la maceta en la mesa) en su lugar.",
      "Juanito: Ándale, Anita. Vámonos.",
      "Anita: Ay, Juanito. Qué nerviosito te pones.",
      "(Juanito agarra una escoba)",
      "Juanito: Mejor ponte a barrer para que Don Peter vea que estamos haciendo algo bueno y no nos vaya a meter a la cárcel.",
      "(Se ponen los dos a barrer)",
      "Anita: Déjame toco la maceta por última vez.",
      "Juanito (repite mientras barre): “Última vez”. Siempre me dices eso. Primero entramos a este lugar sin permiso y después me dices que vamos a jugar un ratito y nunca jugamos.",
      "Juanito: Ya vámonos, porque sí nos pueden meter a la cárcel.",
      "Anita: Ay, Juanito. ¿Cómo crees? No valemos nada, no tenemos papás. No nos pueden meter a la cárcel.",
      "Juanito: ¿¡Ah no!? Mira cómo acabó Pepito la vez pasada. Y eso que les puso una carita a los policías y como quiera se lo llevaron.",
      "Anita: Mira, Juanito. Quisiera ser como esta bonita maceta y que los turistas me vean y me compren para adornar una casa bonita.",
      "Juanito: Ay, Anita. No me digas que eso quieres ser y estar en un pasillito y que te esté dando el Sol ¿Crees que para eso sirves? ¿Para adornar un pasillito?",
      "Anita: Pos sí. En eso quiero convertirme, en una maceta.",
      "Juanito: Oye, Anita. ¿Y yo en qué me podría convertir? ¿Para qué crees que soy bueno?",
      "(Anita da una vuelta alrededor de Juanito)",
      "Anita: Te puedes convertir en un jarrón para cocer frijoles.",
      "EMPIEZA LA CANCIÓN: “PARA QUÉ SIRVES TÚ",
      "DÍA 2",
      "Juanito: Oye, Anita. Me quedé pensando en lo que me dijiste ayer. ¿De verdad crees que me podría convertir en un jarrón para cocer frijoles?",
      "Anita: ¿Cómo ves, Juanito? ¿Te gustaría convertirte en un jarrón para cocer frijoles?",
      "Juanito: No sé, Anita. Pues estaría en el fuego. ¡Qué calor! Mejor en una jarra, para estar más fresco",
      "Juanito: ¡Escucha, Anita. Ahí viene Don Peter!. ¡Vámonos!",
      "(Corren y salen)",
      "Srita. Alma: Oye, Anita. Estoy pensando que muy pronto vendrá el invierno y sería bueno que tú y Juanito regresaran a la Casa Hogar.",
      "Anita: Este ehmmm pues... Por aquí anda Juanito, déjeme le hablo.",
      "Anita (Gritando y yendo a buscar a Juanito): !Juanitoooo!",
      "(Entra Juanito)",
      "Anita: Mira, Juanito. Aquí está la señorita Alma, la Directora de la Casa Hogar. ¿Te acuerdas?",
      "Anita: Viene a invitarnos a que regresemos porque ya viene el invierno",
      "Juanito: Sí, señorita. Muchas gracias. Porque no tenemos chaquetas para cubrirnos del frío y me caería bien un chocolatito calientito con pan (Juanito se saborea)",
      "Anita: Pues yo no, señorita Alma. No me gusta que me estén mandando todo el tiempo",
      "Srita. Alma: Mira, Anita. Cuando vivía tu papá él venía a platicar conmigo porque sabía que iba a morir, y él quería que yo te cuidara.",
      "Srita. Alma: Mira. Anita. En la Biblia tú puedes aprender cómo Dios creó el Universo y al sexto día creó al ser humano del polvo de la Tierra; y dice la Biblia que Dios creó al hombre y a la mujer. Entonces, si tú crees en el Hijo de Dios, que se llama Jesús, y le pides que entre en tu corazón y obedeces su palabra (que es la Biblia) tú puedes ser hija de Dios. Aunque no tengas papá ni mamá, Dios puede ser tu Padre. Dios te hizo especial, Anita. Eres una obra de arte creada por Dios, Anita.",
      "Juanito: ¿Y yo, señorita Alma?",
      "Srita. Alma: Sí, Juanito. Tú también. Ábrele tu corazón a Jesús y también serás hijo de Dios. Así como tú, todos los niños que están en este lugar pueden orar y decirle a Dios que quieren ser sus hijos.",
      "EMPIEZA LA CANCIÓN: “HECHO A MANO”"
    ],
  });
}
